name: NextJS Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install Dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build Next.js Project
      - name: Build Next.js
        run: npm run build

      # 5. SonarQube Scan
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=${{ secrets.SONAR_HOST }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 6. Trivy Installation
      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update -y
          sudo apt-get install -y trivy

      # 7. Trivy Filesystem Scan
      - name: Trivy FS Scan
        run: trivy fs --format table -o fs-report.json .

      # 8. Docker Login
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 9. Docker Build Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/next-js-app:lates .

      # 10. Docker Push Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/next-js-app:lates

      # 11. Deploy & Run Docker Container on GitHub Runner
      - name: Run Docker Container in GitHub Runner
        run: |
          echo "Starting container on GitHub Runner..."
          docker run -d -p 3000:3000 --name nextjs-runner-app ${{ secrets.DOCKER_USERNAME }}/next-js-app:lates
          echo "Container is running!"



      # 10. Deploy on VPS (optional)
   #   - name: Deploy on Server
    #    uses: appleboy/ssh-action@v0.1.7
     #   with:
      #    host: ${{ secrets.SERVER_HOST }}
       #   username: ${{ secrets.SERVER_USER }}
        #  key: ${{ secrets.SERVER_SSH_KEY }}
         # script: |
          #  docker stop nextjs-app || true
           # docker rm nextjs-app || true
            #docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-web:latest
            #docker run -d -p 3000:3000 --name nextjs-app ${{ secrets.DOCKER_USERNAME }}/nextjs-web:latest
